package main

import _ "google.golang.org/protobuf/types/descriptorpb"
import _ "google.golang.org/protobuf/types/dynamicpb"
import _ "google.golang.org/protobuf/types/known/anypb"
import _ "google.golang.org/protobuf/types/known/apipb"
import _ "google.golang.org/protobuf/types/known/durationpb"
import _ "google.golang.org/protobuf/types/known/emptypb"
import _ "google.golang.org/protobuf/types/known/fieldmaskpb"
import _ "google.golang.org/protobuf/types/known/sourcecontextpb"
import _ "google.golang.org/protobuf/types/known/structpb"
import _ "google.golang.org/protobuf/types/known/timestamppb"
import _ "google.golang.org/protobuf/types/known/typepb"
import _ "google.golang.org/protobuf/types/known/wrapperspb"
import _ "google.golang.org/protobuf/types/pluginpb"
