#!/bin/sh
# This script generates a Go file importing all the (recursive) sub-packages of
# google.golang.org/protobuf/types/..., ensuring the respective proto descriptors
# are available in the proto registry.

(
  echo '// Code generated by gen-imports.sh; DO NOT EDIT.'
  echo
  echo "package $GOPACKAGE"
  echo
  go list -f 'import _ "{{.ImportPath}}"' google.golang.org/protobuf/types/...
) | gofmt -s >imports-gen.go
